/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package guice2;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

import com.google.inject.Guice;
import com.google.inject.Injector;

public class App {
	public static void main(String[] args) {

		EntityManagerFactory emf = Persistence.createEntityManagerFactory("SAHIL2");
		EntityManager em = emf.createEntityManager();
		em.getTransaction().begin();
		
		Student st = new Student();
		st.setStidId(15);
		st.setStudName("sahil");
		em.persist(st);
		
		
	Phone p = new Phone();
//		p.setId(1);
		p.setBrandName("realme");
        em.persist(p);

		em.getTransaction().commit();
		
		
		
		
	em.close();
	emf.close();
	
	Injector injector = Guice.createInjector(new StdModule());
	listofstudentImp listofstudentImp =injector.getInstance(listofstudentImp.class);
	listofstudentImp.listofstudent();
	  PhoneListImpl phoneListImpl = injector.getInstance(PhoneListImpl.class);
      phoneListImpl.listPhones();
	
	}
}
